### ISSUE TITLE
Create a LICENSE file

### ISSUE THREAD

**Issue by automoto** [sydneyshile/go-difference-check#1]
Add an MIT license to this repository, similar to what I created here https://github.com/automoto/devlog/blob/master/LICENSE but just update the year and screen name to yours

**Comment by automoto** [comment]
Note: you will need this for your code docs to display here https://pkg.go.dev/github.com/sydneyshile/go-difference-check

**Comment by sydneyshile** [comment]
License file https://github.com/sydneyshile/go-difference-check/blob/main/LICENSE
