### ISSUE TITLE
Create a github actions CI pipeline

### ISSUE THREAD

**Issue by automoto** [sydneyshile/go-difference-check#2]
Create a build pipeline for this repository using github actions.
Make sure common tasks like linting and running unit tests are included in the pipeline

**Comment by sydneyshile** [comment]
Ran CI. Result: https://github.com/sydneyshile/go-difference-check/actions

**Comment by automoto** [comment]
I'd recommend we switch the builds to run on every push, this would allow automatic builds to run on contributors branches which in this case should be safe since we are only running tests and linting.

We should be able to switch this logic out https://github.com/sydneyshile/go-difference-check/blob/main/.github/workflows/go.yml#L6 and change it to `on: [push]` and we can add more restrictions later

**Comment by automoto** [comment]
Also you should add branch protections for main branch soon, ensure we start following the PR needs a green build to pass before we merge to main for good CI.

**Comment by automoto** [comment]
Ill double check if these push settings work. You should consider adding branch protections for main branch to enforce passing PR builds.

**Comment by sydneyshile** [comment]
I have checked push settings on pull request. Branch protection rule updated here: https://github.com/sydneyshile/go-difference-check/settings/branches.
