### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by automoto** [sydneyshile/go-difference-check#3]
We should really ensure the percentages here are correct and have multiple tests with different percentages and we should verify the results are calculated correctly using multiple kinds of calculations, using negative numbers, using decimals etc...

**Comment by sydneyshile** [comment]
https://github.com/sydneyshile/go-difference-check/blob/main/difference_test.go

**Comment by automoto** [comment]
That is a good start, I would try to add more decimal value tests with varying decimal place values and make sure its still correct e.g.

12.55, 50.54678, 12.5 etc...
