### ISSUE TITLE
Update how we do calculations

### ISSUE THREAD

**Issue by automoto** [sydneyshile/go-difference-check#5]
I would change the calculation to be different here:
https://github.com/sydneyshile/go-difference-check/blob/7658de11dacf4ad5db2b8f3aeb8207966623d8b3/difference.go#L22

Instead I did in the past is something like:
```
diff := n1 - n2
average := (n1 + n2) / 2
return (diff/average * 100)

```

**Comment by automoto** [comment]
I don't think we need the absolute value here?

**Comment by automoto** [comment]
Another thing:
We should consider adding error handling, instead of just returning a float we should consider adding an `error` return type and we should do some checks on inputs to make sure they are not negative e.g. if someone passes in a negative number we should return an error stating negatives are not allowed.

**Comment by automoto** [comment]
We should be able to check our answers here for percentage difference https://www.calculatorsoup.com/calculators/algebra/percent-difference-calculator.php

**Comment by automoto** [comment]
Ah I see why we needed the absolute value, I tried this out and it worked:
```
func PercentDifference(n1 float64, n2 float64) float64 {
	diff := math.Abs(n1 - n2)
	average := (n1 + n2) / 2
	return (diff/average * 100)
}
```

**Comment by automoto** [comment]
Note: https://www.calculatorsoup.com/calculators/algebra/percent-difference-calculator.php rounds to the 4th decimal, our answer should be close but it will be different since we won't be rounding

**Comment by sydneyshile** [comment]
Thank you for your inputs, Both calculations are updated.
